##### 1.Sayılardan oluşan bir boyutlu array oluşturun. Arrayi oluştururken sayıların veri tipini integer olarak belirtelim.

Oluşturulan arrayin boyut, eleman sayısı bilgilerine bakalım.

In [4]:
import numpy as np

In [29]:
array = np.array([1,2,3,4,5],dtype=int)
array

array([1, 2, 3, 4, 5])

In [30]:
array.ndim

1

In [31]:
array.size

5

##### 2. Aşağıda verilen iki boyutlu ve üç boyutlu arrayi oluşturalım. Bu arraylerin boyut, eleman sayısı, satır, sütun bilgilerine ulaşalım. 

İki boyutlu array:
[[1,2,6,7],
 [4,3,9,5]]

Üç boyutlu array:
[[[7,5,14],[21,8,11]],
 [[8,6,20],[14,3,9]]]

 

In [8]:
array2 = np.array([[1,2,6,7],[4,3,9,5]])
array3 = np.array([[[7,5,14],[21,8,11]],[[8,6,20],[14,3,9]]])

In [9]:
array2

array([[1, 2, 6, 7],
       [4, 3, 9, 5]])

In [10]:
array3

array([[[ 7,  5, 14],
        [21,  8, 11]],

       [[ 8,  6, 20],
        [14,  3,  9]]])

In [11]:
array2.ndim

2

In [12]:
array3.ndim

3

In [13]:
array2.size

8

In [14]:
array3.size

12

In [15]:
array2.shape

(2, 4)

In [16]:
array3.shape

(2, 2, 3)

##### 3. İstenilen elamanlara ulaşmak için arrayler üzerinde indexleme işlemi yapalım

In [17]:
array2

array([[1, 2, 6, 7],
       [4, 3, 9, 5]])

In [18]:
#İki boyutlu arraydaki 2 elemanına ulaşalım
array2[0,1]

2

In [19]:
#İki boyutlu arraydaki 7 elemanına ulaşalım
array2[0,3]

7

In [20]:
array3

array([[[ 7,  5, 14],
        [21,  8, 11]],

       [[ 8,  6, 20],
        [14,  3,  9]]])

In [21]:
#Üç boyutlu arraydaki 9 elemanına ulaşalım
array3[1,1,2]

9

In [22]:
#Üç boyutlu arraydaki 5 elemanına ulaşalım
array3[0,0,1]

5

##### 4. Arrayler üzerinde slicing işlemi uygulayalım.

In [23]:
array2

array([[1, 2, 6, 7],
       [4, 3, 9, 5]])

In [24]:
#İki boyutlu arraydaki 2,6 elemanlarına ulaşalım
array2[0,1:3]

array([2, 6])

In [25]:
#İki boyutlu arraydaki 3,9,5 elemanlarına ulaşalım
array2[1,1:4]

array([3, 9, 5])

In [26]:
array3

array([[[ 7,  5, 14],
        [21,  8, 11]],

       [[ 8,  6, 20],
        [14,  3,  9]]])

In [27]:
#Üç boyutlu arraydaki 21,8,11 elemanlarına ulaşalım
array3[0,1,0:4]


array([21,  8, 11])

In [28]:
#Üç boyutlu arraydaki 6,20 elemanlarına ulaşalım
array3[1,0,1:4]

array([ 6, 20])

##### 5. 5 satır 3 sütunluk sıfırlardan ve birlerden oluşan iki tane iki boyutlu array oluşturalım. Bu arrayleri satır ve sütun bazında birleştirelim.

In [35]:
array4 = np.zeros((5,3),dtype=int)
array5 = np.ones((5,3),dtype=int)

In [36]:
array4

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [37]:
array5

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [40]:
array6 = np.concatenate((array4,array5),axis=0)
array6

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [43]:
array7 = np.concatenate((array4,array5),axis=1)
array7

array([[0, 0, 0, 1, 1, 1],
       [0, 0, 0, 1, 1, 1],
       [0, 0, 0, 1, 1, 1],
       [0, 0, 0, 1, 1, 1],
       [0, 0, 0, 1, 1, 1]])